### ISSUE TITLE
COT leaflet widget not navigable by keyboard

### ISSUE THREAD

**Issue by KatiRG** [CityofToronto/bdit_cot-vfh#6]
and therefore does not pass accessibility for motor-impaired.

From Evan:
**mapbox keyboard navigation** - it is possible using `keydown` listeners.  see https://docs.mapbox.com/mapbox-gl-js/example/game-controls/ for an example - they've used left / right to rotate the camera, but you could just as easily map all four arrow keys to `panBy()` on a top-down map.

`easing` just controls the transition - any function `f` that maps the unit interval to itself, and such that `f(0) === 0` and `f(1) === 1`, would work as well

**Comment by candu** [comment]
I should also note that Leaflet has keyboard navigation options: https://leafletjs.com/reference-1.6.0.html#map-keyboard
